"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, Check, Play, ShieldCheck, WandSparkles } from "lucide-react";
import "../workspace/workspace.css";
import "./fix.css";

type Finding={id:"coupon"|"place-order";title:string;detail:string;patch:string};
const initial=`<main>\n  <h1>Checkout</h1>\n  <form aria-label="Payment details">\n    <label for="email">Email address</label>\n    <input id="email" type="email" />\n    <input id="coupon" type="text" placeholder="Coupon code" />\n    <button id="place-order" type="submit"><svg aria-hidden="true"></svg></button>\n  </form>\n</main>`;
function inspect(markup:string){const doc=new DOMParser().parseFromString(markup,"text/html");const issues:Finding[]=[];const coupon=doc.querySelector("#coupon");if(coupon&&!coupon.getAttribute("aria-label")&&!doc.querySelector('label[for="coupon"]'))issues.push({id:"coupon",title:"Coupon field has no programmatic label",detail:"Placeholder text is not a persistent label for keyboard and screen-reader users.",patch:'<label for="coupon">Coupon code</label>\n<input id="coupon" type="text" />'});const order=doc.querySelector("#place-order");if(order&&!(order.getAttribute("aria-label")||order.textContent?.trim()))issues.push({id:"place-order",title:"Place-order button has no accessible name",detail:"A screen reader announces an unnamed button, so the action is unclear.",patch:'<button id="place-order" type="submit">Place order</button>'});return issues}
export default function FixPreview(){const[candidate,setCandidate]=useState(initial);const[findings,setFindings]=useState<Finding[]|null>(null);useEffect(()=>setFindings(inspect(candidate)),[candidate]);const apply=(f:Finding)=>{if(f.id==="coupon")setCandidate(v=>v.replace(/<input id="coupon" type="text" placeholder="Coupon code"\s*\/>/,'<label for="coupon">Coupon code</label>\n    <input id="coupon" type="text" />'));if(f.id==="place-order")setCandidate(v=>v.replace(/<button id="place-order" type="submit"><svg aria-hidden="true"><\/svg><\/button>/,'<button id="place-order" type="submit">Place order</button>'))};return <main className="studio"><nav><a href="/" className="back"><ArrowLeft size={16}/> Playground</a><b><span>◈</span> AccessTrace Fix Preview</b><span/></nav><section className="intro"><p>DETECT → FIX → VERIFY</p><h1>Turn a regression into a verified patch.</h1><span>Every suggestion is visible, editable, and rechecked after it is applied.</span></section><section className="studio-grid"><aside><div className="project"><p>CANDIDATE BRANCH</p><h3>Checkout flow</h3><small>2 known accessibility regressions</small></div><p className="aside-label">FIX WORKFLOW</p><div className="step"><span><b>1. Detect</b><small>Find failing semantics</small></span></div><div className="step"><span><b>2. Apply</b><small>Review exact patch</small></span></div><div className="step"><span><b>3. Verify</b><small>Rescan candidate</small></span></div></aside><div className="canvas"><div className="workhead"><div><p>CANDIDATE · CURRENT BRANCH</p><h2>Checkout markup</h2></div><button onClick={()=>setFindings(inspect(candidate))}><Play size={15} fill="currentColor"/> Re-run check</button></div><textarea value={candidate} onChange={e=>setCandidate(e.target.value)} spellCheck={false}/>{!findings?<div className="report loading-report">Preparing local check…</div>:findings.length?<div className="report"><div className="score"><div><p>REMEDIATION QUEUE</p><h2>{findings.length} safe fix{findings.length>1?"es":""} available</h2></div><span className="warn"><WandSparkles size={15}/> Review patches</span></div><div className="issues">{findings.map(f=><article key={f.id}><i className="critical"/><div><b>{f.title}</b><p>{f.detail}</p><pre>{f.patch}</pre><button className="apply" onClick={()=>apply(f)}><WandSparkles size={14}/> Apply this patch</button></div></article>)}</div></div>:<div className="report"><div className="score"><div><p>VERIFIED CANDIDATE</p><h2>No supported regressions remain</h2></div><span className="good"><Check size={15}/> Verified</span></div><p className="clean"><ShieldCheck size={21}/> The candidate now has an accessible coupon label and a named place-order button.</p></div>}</div></section></main>}
